In [53]:
#this code is used to prepare and clean the bike share data for the Cyclistic bike share case study 
#this data contains 12 months of bike ride data and exists in 12 separate csv files. 
#the files must be imported, concatenated, and then the data will be prepared and cleaned for analysis. 

#import numpy and pandas
import numpy as np
import pandas as pd

IMPORT FILES AND JOIN

In [54]:
#import the csv files and create dataframes. Imports datasets for April 2025-March 2026


df0425=pd.read_csv(r'C:\Users\madse\OneDrive\Documents\Data Analytics Certificate\Case Study 1_ Cyclistics\Extracted CSV Files\202504-divvy-tripdata.csv')
df0525=pd.read_csv(r'C:\Users\madse\OneDrive\Documents\Data Analytics Certificate\Case Study 1_ Cyclistics\Extracted CSV Files\202505-divvy-tripdata.csv')
df0625=pd.read_csv(r'C:\Users\madse\OneDrive\Documents\Data Analytics Certificate\Case Study 1_ Cyclistics\Extracted CSV Files\202506-divvy-tripdata.csv')
df0725=pd.read_csv(r'C:\Users\madse\OneDrive\Documents\Data Analytics Certificate\Case Study 1_ Cyclistics\Extracted CSV Files\202507-divvy-tripdata.csv')
df0825=pd.read_csv(r'C:\Users\madse\OneDrive\Documents\Data Analytics Certificate\Case Study 1_ Cyclistics\Extracted CSV Files\202508-divvy-tripdata.csv')
df0925=pd.read_csv(r'C:\Users\madse\OneDrive\Documents\Data Analytics Certificate\Case Study 1_ Cyclistics\Extracted CSV Files\202509-divvy-tripdata.csv')
df1025=pd.read_csv(r'C:\Users\madse\OneDrive\Documents\Data Analytics Certificate\Case Study 1_ Cyclistics\Extracted CSV Files\202510-divvy-tripdata.csv')
df1125=pd.read_csv(r'C:\Users\madse\OneDrive\Documents\Data Analytics Certificate\Case Study 1_ Cyclistics\Extracted CSV Files\202511-divvy-tripdata.csv')
df1225=pd.read_csv(r'C:\Users\madse\OneDrive\Documents\Data Analytics Certificate\Case Study 1_ Cyclistics\Extracted CSV Files\202512-divvy-tripdata.csv')
df0126=pd.read_csv(r'C:\Users\madse\OneDrive\Documents\Data Analytics Certificate\Case Study 1_ Cyclistics\Extracted CSV Files\202601-divvy-tripdata.csv')
df0226=pd.read_csv(r'C:\Users\madse\OneDrive\Documents\Data Analytics Certificate\Case Study 1_ Cyclistics\Extracted CSV Files\202602-divvy-tripdata.csv')
df0326=pd.read_csv(r'C:\Users\madse\OneDrive\Documents\Data Analytics Certificate\Case Study 1_ Cyclistics\Extracted CSV Files\202603-divvy-tripdata.csv')

In [55]:
#verify each dataset
df0425.head(10)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,AF3863596DF9D94B,classic_bike,2025-04-27 14:29:34.619,2025-04-27 14:36:23.584,Troy St & Elston Ave,15631,Richmond St & Diversey Ave,15645,41.945244,-87.706650,41.931902,-87.701195,member
1,8B38081EBE918800,electric_bike,2025-04-23 17:48:51.863,2025-04-23 17:59:06.015,Wabash Ave & Adams St,KA1503000015,Green St & Madison St,TA1307000120,41.879472,-87.625689,41.881859,-87.649264,member
2,1C7F1DE826BBBC8D,electric_bike,2025-04-05 17:55:30.845,2025-04-05 18:05:40.032,Damen Ave & Cortland St,13133,California Ave & Fletcher St,15642,41.915983,-87.677335,41.938429,-87.698008,member
3,CAD23D69A79A6C3B,classic_bike,2025-04-03 08:22:04.493,2025-04-03 08:32:06.099,Clark St & Elm St,TA1307000039,Orleans St & Merchandise Mart Plaza,TA1305000022,41.902973,-87.631280,41.888243,-87.636390,member
4,BE241E601482E0AB,electric_bike,2025-04-15 06:09:55.293,2025-04-15 06:19:58.942,Western Ave & Walton St,KA1504000103,Damen Ave & Charleston St,13288,41.898418,-87.686596,41.920082,-87.677855,member
5,752C0388D68EBBE5,electric_bike,2025-04-16 08:33:34.516,2025-04-16 08:41:49.998,Western Ave & Walton St,KA1504000103,Damen Ave & Charleston St,13288,41.898418,-87.686596,41.920082,-87.677855,member
6,C2C6CE2F046E4B4A,classic_bike,2025-04-26 17:11:59.253,2025-04-26 17:29:09.295,Lincoln Ave & Roscoe St*,chargingstx5,Broadway & Cornelia Ave,13278,41.943350,-87.670668,41.945529,-87.646439,member
7,D1004EF94E7957C3,electric_bike,2025-04-19 15:28:47.620,2025-04-19 15:49:30.801,Damen Ave & Cortland St,13133,Broadway & Wilson Ave,13074,41.915983,-87.677335,41.965221,-87.658139,member
8,95DC50DED42F7876,classic_bike,2025-04-29 19:19:32.788,2025-04-29 19:24:02.678,Clark St & Elm St,TA1307000039,Clark St & North Ave,13128,41.903322,-87.632999,41.911974,-87.631942,member
9,5CB06C086A4C8C21,classic_bike,2025-04-09 16:08:21.766,2025-04-09 16:52:59.793,Michigan Ave & Madison St,13036,Wabash Ave & Grand Ave,TA1307000117,41.882134,-87.625125,41.891466,-87.626761,casual

In [56]:
#check info on several dataframes to verify they will stack correctly

df0425.info()
df0525.info()
df0226.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 371341 entries, 0 to 371340
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             371341 non-null  object
 1   rideable_type       371341 non-null  object
 2   started_at          371341 non-null  object
 3   ended_at            371341 non-null  object
 4   start_station_name  300145 non-null  object
 5   start_station_id    300145 non-null  object
 6   end_station_name    297706 non-null  object
 7   end_station_id      297706 non-null  object
 8   start_lat           371341 non-null  float64
 9   start_lng           371341 non-null  float64
 10  end_lat             371052 non-null  float64
 11  end_lng             371052 non-null  float64
 12  member_casual       371341 non-null  object
dtypes: float64(4), object(9)
memory usage: 36.8+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 502456 entries, 0 to 502455
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             502456 non-null  object
 1   rideable_type       502456 non-null  object
 2   started_at          502456 non-null  object
 3   ended_at            502456 non-null  object
 4   start_station_name  399096 non-null  object
 5   start_station_id    399096 non-null  object
 6   end_station_name    395020 non-null  object
 7   end_station_id      395020 non-null  object
 8   start_lat           502456 non-null  float64
 9   start_lng           502456 non-null  float64
 10  end_lat             501905 non-null  float64
 11  end_lng             501905 non-null  float64
 12  member_casual       502456 non-null  object
dtypes: float64(4), object(9)
memory usage: 49.8+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201450 entries, 0 to 201449
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             201450 non-null  object
 1   rideable_type       201450 non-null  object
 2   started_at          201450 non-null  object
 3   ended_at            201450 non-null  object
 4   start_station_name  169381 non-null  object
 5   start_station_id    169381 non-null  object
 6   end_station_name    166589 non-null  object
 7   end_station_id      166589 non-null  object
 8   start_lat           201450 non-null  float64
 9   start_lng           201450 non-null  float64
 10  end_lat             201321 non-null  float64
 11  end_lng             201321 non-null  float64
 12  member_casual       201450 non-null  object
dtypes: float64(4), object(9)
memory usage: 20.0+ MB

In [57]:
#concatenate the 12 datasets

year_data = pd.concat([df0425, df0525, df0625, df0725, df0825, df0925, df1025, df1125, df1225, df0126, df0226, df0326], axis = 0)

In [58]:
year_data.info() #check info of the dataset

<class 'pandas.core.frame.DataFrame'>
Index: 5620544 entries, 0 to 317036
Data columns (total 13 columns):
 #   Column              Dtype
---  ------              -----
 0   ride_id             object
 1   rideable_type       object
 2   started_at          object
 3   ended_at            object
 4   start_station_name  object
 5   start_station_id    object
 6   end_station_name    object
 7   end_station_id      object
 8   start_lat           float64
 9   start_lng           float64
 10  end_lat             float64
 11  end_lng             float64
 12  member_casual       object
dtypes: float64(4), object(9)
memory usage: 600.3+ MB

BEGIN CLEANING

In [59]:
#convert start and end times to datetime 
year_data['started_at']=pd.to_datetime(year_data['started_at']) 
year_data['ended_at']=pd.to_datetime(year_data['ended_at'])

#create new column ride length that is the difference between end and start time 
year_data ['ride_length'] =(year_data.ended_at)-(year_data.started_at)
print(year_data['ride_length'].dtype) #check that data type is timedelta

timedelta64[ns]

In [60]:
#make sure ride length is timedelta 
year_data['ride_length']=pd.to_timedelta(year_data['ride_length'], errors='coerce') 

#ride_length converted to mins  
year_data['ride_length']=(year_data['ride_length'].dt.total_seconds() / 60).round(2)

In [61]:
#create a new column with day of week of each trip 
year_data['day_of_week'] = year_data['started_at'].dt.day_name()

In [62]:
#check data nulls
year_data.isnull().sum()

ride_id                     0
rideable_type               0
started_at                  0
ended_at                    0
start_station_name    1194952
start_station_id      1194952
end_station_name      1259214
end_station_id        1259214
start_lat                   0
start_lng                   0
end_lat                  5784
end_lng                  5784
member_casual               0
ride_length                 0
day_of_week                 0
dtype: int64

In [63]:
#fill nulls with NO DATA 
year_data=year_data.fillna('NO DATA')

In [64]:
#check start and end station ids 
year_data['start_station_id'].value_counts()
year_data['end_station_id'].value_counts()

end_station_id
NO DATA     1259214
CHI01747      57299
CHI00374      32152
CHI00299      30652
CHI00525      30368
             ...
1170.0            1
907               1
1087.0            1
918               1
1097.0            1
Name: count, Length: 3325, dtype: int64

In [65]:
#convert station ids to string type 
str(year_data['start_station_id'])
str(year_data['end_station_id'])

#creates columns to check the id lengths 
year_data['start_id_length']=year_data['start_station_id'].astype(str).str.len()
year_data['end_id_length']=year_data['end_station_id'].astype(str).str.len()

In [66]:
year_data['start_id_length'].value_counts() #check the lengths of the start ids for understanding

start_id_length
8     3724102
7     1200280
12     328171
5      287910
3       37433
6       28781
9        4731
17       3205
4        2908
13       1651
10       1341
14         25
35          6
Name: count, dtype: int64

In [67]:
year_data['end_id_length'].value_counts() #check the lengths of the end ids for understanding

end_id_length
8     3666358
7     1264478
12     326784
5      285314
3       36804
6       28115
9        3332
17       3319
4        2884
13       1741
10       1384
14         25
35          6
Name: count, dtype: int64

In [68]:
year_data['start_station_name'].value_counts() #understand top 5 most recurring start station names

start_station_name
NO DATA                                 1194952
DuSable Lake Shore Dr & Monroe St         39761
Navy Pier                                 38963
Michigan Ave & Oak St                     35466
Kingsbury St & Kinzie St                  34242
                                         ...
Public Rack - May St & 78th St                1
Public Rack - Parnell Ave & 98th St           1
Public Rack - Mason Ave & Archer Ave          1
Public Rack - Ewing Ave & 101st St            1
Harlem Ave & Roscoe St                        1
Name: count, Length: 1892, dtype: int64

In [69]:
year_data['end_station_name'].value_counts() #understand top 5 most recurring end station names

end_station_name
NO DATA                                            1259214
Navy Pier                                            38484
DuSable Lake Shore Dr & Monroe St                    37999
Michigan Ave & Oak St                                34957
DuSable Lake Shore Dr & North Blvd                   34810
                                                    ...
Public Rack - Mozart & 79th                              1
Public Rack - Western Ave & 107th St                     1
Public Rack - Vincennes Ave & 91st St                    1
Public Rack - Western Ave & 98th St                      1
Public Rack - William Rainey Harper High School          1
Name: count, Length: 1901, dtype: int64

In [70]:
year_data.groupby('start_station_name')['start_station_id'].nunique().sort_values(ascending=False) 
#shows that some start station names have more than 1 unique start station id

start_station_name
Clark St & Lake St                       4
Burling St & Diversey Pkwy               4
Kedzie Ave & Jackson Blvd                4
Daley Center Plaza                       4
Franklin St & Monroe St                  4
                                        ..
Public Rack - Kimball & Ardmore          1
Public Rack - King Dr & 83rd St          1
Public Rack - Kinzua Ave & Devon Ave     1
Public Rack - Komensky Ave & 26th St     1
[Archived] Wilton Ave & Diversey Pkwy    1
Name: start_station_id, Length: 1892, dtype: int64

In [71]:
year_data.groupby('start_station_id')['start_station_name'].nunique().sort_values(ascending=False)
#shows that some start station ids have more than 1 unique start station name

start_station_id
CHI01756        3
CHI01665        3
CHI01747        3
657             2
CHI00254        2
               ..
922             1
924             1
927             1
929             1
chargingstx5    1
Name: start_station_name, Length: 3302, dtype: int64

In [72]:
year_data.groupby('start_station_name')['start_station_id'].unique() #looks at different ids for top 5 start stations

start_station_name
2112 W Peterson Ave                      [KA1504000155, CHI00611]
21st St & Pulaski Rd                            [21331, CHI01823]
63rd St Beach                                   [15491, CHI00315]
900 W Harrison St                               [13028, CHI01748]
Aberdeen St & 103rd St                          [24425, CHI01976]
                                                   ...
Woodlawn Ave & Lake Park Ave             [KA1503000065, CHI00334]
Yates Ave & 95th St                                    [CHI00854]
Yates Blvd & 75th St                     [KA1503000024, CHI00573]
Yates Blvd & 93rd St                            [20237, CHI00856]
[Archived] Wilton Ave & Diversey Pkwy                  [CHI00226]
Name: start_station_id, Length: 1892, dtype: object

In [73]:
year_data.groupby('end_station_name')['end_station_id'].unique() #checks for end station names and ids

end_station_name
2112 W Peterson Ave                      [KA1504000155, CHI00611]
21st St & Pulaski Rd                            [21331, CHI01823]
63rd St Beach                                   [15491, CHI00315]
900 W Harrison St                               [13028, CHI01748]
Aberdeen St & 103rd St                          [24425, CHI01976]
                                                   ...
Woodlawn Ave & Lake Park Ave             [KA1503000065, CHI00334]
Yates Ave & 95th St                                    [CHI00854]
Yates Blvd & 75th St                     [KA1503000024, CHI00573]
Yates Blvd & 93rd St                            [20237, CHI00856]
[Archived] Wilton Ave & Diversey Pkwy                  [CHI00226]
Name: end_station_id, Length: 1901, dtype: object

In [74]:
#create new column for routes 
year_data['route']=year_data['start_station_name'] + ' and ' + year_data['end_station_name']

year_data['route'].value_counts()

route
NO DATA and NO DATA                                                        572867
DuSable Lake Shore Dr & Monroe St and DuSable Lake Shore Dr & Monroe St      6755
Navy Pier and Navy Pier                                                      6498
Kingsbury St & Kinzie St and NO DATA                                         5101
Wells St & Concord Ln and NO DATA                                            4912
                                                                            ...
Damen Ave & Leland Ave and Broadway & Oakdale Ave                               1
Clark/Newport Corral and Wells St & Madison St                                  1
Public Rack - Prairie Ave & Garfield Blvd S and Drexel Ave & 60th St            1
California Ave & Byron St and Clark/Newport Corral                              1
Pine Grove Ave & Waveland Ave and Central Park Ave & Elbridge Ave               1
Name: count, Length: 235016, dtype: int64

In [75]:
#verify that there are no duplicate ride ids 
year_data['ride_id'].duplicated().any()

np.False_

In [76]:
#verify that there are no duplicate rows 
year_data.duplicated().any()

np.False_

In [77]:
year_data.ride_id.dtype #checks data type of ride_id

dtype('O')

In [78]:
#create new column for ride id length with string lengths of the ride id 
#verify that they are all 16 characters
year_data['ride_id_length']=year_data['ride_id'].astype(str).str.len() 
year_data.ride_id_length.value_counts()

ride_id_length
16    5620544
Name: count, dtype: int64

In [79]:
#validate bike type data
year_data['rideable_type'].value_counts()

rideable_type
electric_bike    3678925
classic_bike     1941619
Name: count, dtype: int64

In [80]:
#validate rider type data
year_data['member_casual'].value_counts()

member_casual
member    3605045
casual    2015499
Name: count, dtype: int64

In [81]:
#rename member casual column 
year_data = year_data.rename(columns={'member_casual': 'member_type'})

In [82]:
#validate day of week data
year_data['day_of_week'].value_counts()

day_of_week
Saturday     867853
Friday       844808
Thursday     841038
Tuesday      808783
Wednesday    786669
Monday       745678
Sunday       725715
Name: count, dtype: int64

In [83]:
#check stats on ride lengths to identify any issues
year_data.ride_length.describe()

count    5.620544e+06
mean     1.607593e+01
std      5.576108e+01
min     -5.479000e+01
25%      5.390000e+00
50%      9.420000e+00
75%      1.657000e+01
max      1.574900e+03
Name: ride_length, dtype: float64

In [84]:
#create a filter for ride lengths that are negative and check how many there are
year_data['bad_ride_length']=year_data['ride_length']<0
year_data.bad_ride_length.value_counts()

bad_ride_length
False    5620515
True          29
Name: count, dtype: int64

In [85]:
#create table with just negative ride lengths 
bad_rides=year_data[year_data['ride_length']<0]
bad_rides

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_type,ride_length,day_of_week,start_id_length,end_id_length,route,ride_id_length,bad_ride_length
25121,5D010AFEA6850513,electric_bike,2025-11-02 01:52:37.475,2025-11-02 01:13:24.728,Pine Grove Ave & Wellington Ave,CHI02158,Wilton Ave & Addison St,CHI02055,41.936510,-87.641190,41.947459,-87.653216,member,-39.21,Sunday,8,8,Pine Grove Ave & Wellington Ave and Wilton Ave...,16,True
26669,D1E5316AD88ECD45,classic_bike,2025-11-02 01:50:39.702,2025-11-02 01:14:04.164,Clark St & Ida B Wells Dr,CHI00216,Paulina St & Division St,CHI00244,41.875933,-87.630585,41.903553,-87.670429,casual,-36.59,Sunday,8,8,Clark St & Ida B Wells Dr and Paulina St & Div...,16,True
28663,3AF2F8908C9386F8,classic_bike,2025-11-02 01:57:57.512,2025-11-02 01:33:52.225,State St & Chicago Ave,CHI01772,Ravenswood Ave & Berteau Ave,CHI00471,41.896617,-87.628579,41.957921,-87.673567,member,-24.09,Sunday,8,8,State St & Chicago Ave and Ravenswood Ave & Be...,16,True
43559,19386939ECD81B33,electric_bike,2025-11-02 01:55:34.399,2025-11-02 01:21:31.873,Broadway & Sheridan Rd,CHI00476,NO DATA,NO DATA,41.952833,-87.649993,41.96,-87.74,member,-34.04,Sunday,8,7,Broadway & Sheridan Rd and NO DATA,16,True
51927,083534D28DA37F72,classic_bike,2025-11-02 01:17:57.001,2025-11-02 01:05:27.752,Clark St & Grace St,CHI00301,Grace St & Central Ave,CHI01799,41.950780,-87.659172,41.949533,-87.767265,member,-12.49,Sunday,8,8,Clark St & Grace St and Grace St & Central Ave,16,True
96512,4A659F1BB40EDBF7,electric_bike,2025-11-02 01:55:38.177,2025-11-02 01:04:35.315,Keystone Ave & Montrose Ave,CHI00643,Lynch Ave & Elston Ave,CHI02000,41.961108,-87.728970,41.98096,-87.76149,casual,-51.05,Sunday,8,8,Keystone Ave & Montrose Ave and Lynch Ave & El...,16,True
122065,DA5386E5759667EC,electric_bike,2025-11-02 01:51:31.704,2025-11-02 01:05:47.339,Racine Ave & Belmont Ave,CHI00411,Dearborn St & Division St,CHI02125,41.939743,-87.658865,41.9043,-87.62991,member,-45.74,Sunday,8,8,Racine Ave & Belmont Ave and Dearborn St & Div...,16,True
127523,985A3462DAACFFCF,classic_bike,2025-11-02 01:59:07.835,2025-11-02 01:05:19.214,Seminary Ave & Belden Ave,CHI02106,Sedgwick St & Webster Ave,CHI00487,41.923390,-87.655990,41.922167,-87.638888,member,-53.81,Sunday,8,8,Seminary Ave & Belden Ave and Sedgwick St & We...,16,True
147446,434E3D11ABA96891,electric_bike,2025-11-02 01:59:40.156,2025-11-02 01:08:51.303,Public Rack - Olmstead Ave & Oliphant Ave,CHI01613,Milwaukee Ave & Highland Ave,CHI02015,42.002311,-87.817095,41.99636,-87.78674,casual,-50.81,Sunday,8,8,Public Rack - Olmstead Ave & Oliphant Ave and ...,16,True
157264,9288498F5630E3AD,electric_bike,2025-11-02 01:49:48.360,2025-11-02 01:02:40.976,Damen Ave & Thomas St (Augusta Blvd),CHI00296,NO DATA,NO DATA,41.901315,-87.677409,41.87,-87.68,casual,-47.12,Sunday,8,7,Damen Ave & Thomas St (Augusta Blvd) and NO DATA,16,True
157281,12E0A9A586A45DE3,electric_bike,2025-11-02 01:49:41.788,2025-11-02 01:02:30.041,Damen Ave & Thomas St (Augusta Blvd),CHI00296,NO DATA,NO DATA,41.901315,-87.677409,41.87,-87.68,member,-47.20,Sunday,8,7,Damen Ave & Thomas St (Augusta Blvd) and NO DATA,16,True
158649,222A5E8650C55311,electric_bike,2025-11-02 01:55:51.266,2025-11-02 01:01:50.026,W Armitage Ave & N Sheffield Ave,CHI00836,NO DATA,NO DATA,41.917805,-87.653449,41.91,-87.64,member,-54.02,Sunday,8,7,W Armitage Ave & N Sheffield Ave and NO DATA,16,True
167417,83995E751A0DB5D5,electric_bike,2025-11-02 01:50:50.530,2025-11-02 01:01:15.026,Paulina St & Division St,CHI00244,Kedzie Ave & Milwaukee Ave,CHI00378,41.903553,-87.670429,41.929714,-87.707988,member,-49.59,Sunday,8,8,Paulina St & Division St and Kedzie Ave & Milw...,16,True
200471,120BC0544C3B92E4,classic_bike,2025-11-02 01:41:32.055,2025-11-02 01:08:10.359,Clark St & Chicago Ave,CHI00351,Clark St & Wrightwood Ave,CHI00287,41.896750,-87.630890,41.929546,-87.643118,casual,-33.36,Sunday,8,8,Clark St & Chicago Ave and Clark St & Wrightwo...,16,True
200575,4446901DBDE0531B,classic_bike,2025-11-02 01:45:25.021,2025-11-02 01:08:08.134,Clark St & Chicago Ave,CHI00351,Clark St & Wrightwood Ave,CHI00287,41.896750,-87.630890,41.929546,-87.643118,casual,-37.28,Sunday,8,8,Clark St & Chicago Ave and Clark St & Wrightwo...,16,True
211661,ED8C9D500F271C3D,classic_bike,2025-11-02 01:57:24.553,2025-11-02 01:02:44.165,Racine Ave & Randolph St,CHI00320,Ogden Ave & Chicago Ave,CHI00275,41.884081,-87.656921,41.896362,-87.654061,member,-54.67,Sunday,8,8,Racine Ave & Randolph St and Ogden Ave & Chica...,16,True
213019,4976DE4C5F1AA516,electric_bike,2025-11-02 01:56:44.152,2025-11-02 01:06:51.164,NO DATA,NO DATA,Sedgwick St & Huron St,CHI00241,41.920000,-87.640000,41.894666,-87.638437,member,-49.88,Sunday,7,8,NO DATA and Sedgwick St & Huron St,16,True
213396,3301C8D1FF15E4CE,electric_bike,2025-11-02 01:58:08.316,2025-11-02 01:16:43.649,Manor Ave & Leland Ave,CHI00633,Damen Ave & Division St,CHI00318,41.965875,-87.700825,41.903266,-87.678435,member,-41.41,Sunday,8,8,Manor Ave & Leland Ave and Damen Ave & Divisio...,16,True
235211,A66DEC9146C488BF,electric_bike,2025-11-02 01:50:17.559,2025-11-02 01:07:46.445,NO DATA,NO DATA,Wilton Ave & Addison St,CHI02055,42.000000,-87.670000,41.947459,-87.653216,member,-42.52,Sunday,7,8,NO DATA and Wilton Ave & Addison St,16,True
237480,595AED6AB9A66E8F,classic_bike,2025-11-02 01:51:37.195,2025-11-02 01:18:08.912,Michigan Ave & Oak St,CHI00252,Sedgwick St & Webster Ave,CHI00487,41.900960,-87.623777,41.922167,-87.638888,member,-33.47,Sunday,8,8,Michigan Ave & Oak St and Sedgwick St & Webste...,16,True
241020,5740B9AA6176D32C,classic_bike,2025-11-02 01:59:56.801,2025-11-02 01:05:09.113,Western Blvd & 48th Pl,CHI00735,Campbell Ave & 51st St,CHI01918,41.805661,-87.683392,41.80094,-87.68676,member,-54.79,Sunday,8,8,Western Blvd & 48th Pl and Campbell Ave & 51st St,16,True
260584,A61B896123C0D647,classic_bike,2025-11-02 01:28:03.715,2025-11-02 01:05:17.029,Sacramento Ave & Lyndale St,CHI02126,Rush St & Cedar St,CHI00537,41.922350,-87.702410,41.902309,-87.627691,casual,-22.78,Sunday,8,8,Sacramento Ave & Lyndale St and Rush St & Ceda...,16,True
263836,093B3FC8E465DA4A,electric_bike,2025-11-02 01:52:58.523,2025-11-02 01:04:31.464,NO DATA,NO DATA,Wabash Ave & Roosevelt Rd,CHI00524,41.860000,-87.620000,41.867227,-87.625961,member,-48.45,Sunday,7,8,NO DATA and Wabash Ave & Roosevelt Rd,16,True
265311,C89AFBD919D615FD,classic_bike,2025-11-02 01:51:49.264,2025-11-02 01:18:50.977,Sedgwick St & Huron St,CHI00241,Southport Ave & Irving Park Rd,CHI00481,41.894666,-87.638437,41.954177,-87.664358,member,-32.97,Sunday,8,8,Sedgwick St & Huron St and Southport Ave & Irv...,16,True
274824,8BF21DA40F846779,electric_bike,2025-11-02 01:57:17.456,2025-11-02 01:26:23.644,Campbell Ave & North Ave,CHI00341,Campbell Ave & North Ave,CHI00341,41.910535,-87.689556,41.910535,-87.689556,member,-30.90,Sunday,8,8,Campbell Ave & North Ave and Campbell Ave & No...,16,True
276236,01C21B340CC1EEDA,classic_bike,2025-11-02 01:50:43.657,2025-11-02 01:03:13.912,California Ave & Milwaukee Ave,CHI00307,Paulina Ave & North Ave,CHI00258,41.922695,-87.697153,41.909855,-87.66993,casual,-47.50,Sunday,8,8,California Ave & Milwaukee Ave and Paulina Ave...,16,True
277378,F87FA50B8D40FA97,electric_bike,2025-11-02 01:54:25.185,2025-11-02 01:10:50.859,NO DATA,NO DATA,Michigan Ave & Madison St,CHI01915,41.880000,-87.640000,41.882134,-87.625125,casual,-43.57,Sunday,7,8,NO DATA and Michigan Ave & Madison St,16,True
309959,5F7692C857079901,electric_bike,2025-11-02 01:54:17.357,2025-11-02 01:13:50.718,Clark St & Leland Ave,CHI00461,NO DATA,NO DATA,41.967088,-87.667291,41.96,-87.66,member,-40.44,Sunday,8,7,Clark St & Leland Ave and NO DATA,16,True
342951,E37AEB3E9CE2343E,electric_bike,2025-11-02 01:56:26.465,2025-11-02 01:03:08.183,Broadway & Roscoe Ave,CHI02153,NO DATA,NO DATA,41.943600,-87.645320,41.96,-87.65,member,-53.30,Sunday,8,7,Broadway & Roscoe Ave and NO DATA,16,True

In [86]:
#filter out negative ride lengths
year_data=year_data[year_data['bad_ride_length']==False]
year_data.bad_ride_length.value_counts()

bad_ride_length
False    5620515
Name: count, dtype: int64

In [87]:
#create start and end day columns
year_data['start_day']=year_data.started_at.dt.date
year_data['end_day']=year_data.ended_at.dt.date

#create ride month column 
year_data['ride_month']=year_data.started_at.dt.month_name()
year_data.ride_month.value_counts()

ride_month
August       790317
July         763458
September    714562
June         678801
October      646096
May          502615
April        371376
November     356483
March        317026
February     201454
December     140545
January      137782
Name: count, dtype: int64

In [88]:
#created ride year column 
year_data['ride_year']=year_data.started_at.dt.year
year_data.ride_year.value_counts()

ride_year
2025    4964264
2026     656251
Name: count, dtype: int64

In [89]:
#check 95 and 99% quantiles of ride length
year_data['ride_length'].quantile([0.95, 0.99])
#shows 99% of rides are under 90 minutes

0.95    39.72
0.99    89.39
Name: ride_length, dtype: float64

In [90]:
#check 1 and 5% quantiles of ride length
year_data['ride_length'].quantile([0.01, 0.05])
#1% of rides are shorter than 0.26 mins and 5% lower than 2 mins

0.01    0.26
0.05    2.07
Name: ride_length, dtype: float64

In [91]:
#filter for trips longer than 3 hours
long_trip=year_data[year_data.ride_length>180]
long_trip

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,day_of_week,start_id_length,end_id_length,route,ride_id_length,bad_ride_length,start_day,end_day,ride_month,ride_year
472,1168D33D3361814F,classic_bike,2025-04-17 08:09:32.019,2025-04-17 18:14:22.686,Damen Ave & Foster Ave,KA1504000149,Damen Ave & Foster Ave,KA1504000149,41.975811,-87.679510,...,Thursday,12,12,Damen Ave & Foster Ave and Damen Ave & Foster Ave,16,False,2025-04-17,2025-04-17,April,2025
628,1F897BA26B40512E,classic_bike,2025-04-29 17:03:16.426,2025-04-29 20:52:53.610,Desplaines St & Kinzie St,TA1306000003,Michigan Ave & Ida B Wells Dr,TA1305000010,41.888716,-87.644448,...,Tuesday,12,12,Desplaines St & Kinzie St and Michigan Ave & I...,16,False,2025-04-29,2025-04-29,April,2025
836,43B99662DCC4D061,classic_bike,2025-04-20 12:44:35.001,2025-04-21 08:27:40.172,Broadway & Barry Ave,13137,Franklin St & Jackson Blvd,TA1305000025,41.937582,-87.644098,...,Sunday,5,12,Broadway & Barry Ave and Franklin St & Jackson...,16,False,2025-04-20,2025-04-21,April,2025
1491,026C0081B79B5AF2,classic_bike,2025-04-15 22:16:19.786,2025-04-16 01:37:28.556,Morgan St & Lake St*,chargingstx4,Ogden Ave & Race Ave,13194,41.885492,-87.652289,...,Tuesday,12,5,Morgan St & Lake St* and Ogden Ave & Race Ave,16,False,2025-04-15,2025-04-16,April,2025
4015,62D92944914D6A2B,classic_bike,2025-04-05 20:31:14.057,2025-04-06 01:48:23.152,DuSable Lake Shore Dr & North Blvd,LF-005,State St & Randolph St,TA1305000029,41.911722,-87.626804,...,Saturday,6,12,DuSable Lake Shore Dr & North Blvd and State S...,16,False,2025-04-05,2025-04-06,April,2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314326,740561BE9FD51C93,electric_bike,2026-03-02 14:17:42.406,2026-03-02 17:45:15.272,California Ave & Milwaukee Ave,CHI00307,Ashland Ave & Chicago Ave,CHI00338,41.922695,-87.697153,...,Monday,8,8,California Ave & Milwaukee Ave and Ashland Ave...,16,False,2026-03-02,2026-03-02,March,2026
315334,BCDE7641F3987A6C,classic_bike,2026-03-12 05:53:07.571,2026-03-12 15:33:48.519,Clark St & Lake St,CHI00761,St. Clair St & Erie St 1,CHI01744,41.886021,-87.630876,...,Thursday,8,8,Clark St & Lake St and St. Clair St & Erie St 1,16,False,2026-03-12,2026-03-12,March,2026
315446,B69498DC2EDC1A55,classic_bike,2026-03-29 00:31:32.217,2026-03-29 08:11:47.843,California Ave & Cortez St,CHI00700,California Ave & North Ave,CHI00268,41.900363,-87.696704,...,Sunday,8,8,California Ave & Cortez St and California Ave ...,16,False,2026-03-29,2026-03-29,March,2026
316220,20D3CA3745B3691C,classic_bike,2026-03-27 14:07:22.271,2026-03-27 21:30:15.066,Blackstone Ave & 59th St,CHI01806,University Ave & 57th St,CHI00551,41.787877,-87.590461,...,Friday,8,8,Blackstone Ave & 59th St and University Ave & ...,16,False,2026-03-27,2026-03-27,March,2026
316446,E0B662B7ACADAE3F,classic_bike,2026-03-21 15:54:36.687,2026-03-21 19:34:51.501,Wilton Ave & Belmont Ave,CHI00353,Southport Ave & Waveland Ave,CHI00336,41.940232,-87.652944,...,Saturday,8,8,Wilton Ave & Belmont Ave and Southport Ave & W...,16,False,2026-03-21,2026-03-21,March,2026

In [92]:
#filter for trips shorter than half a minute
short_trip =year_data[year_data.ride_length<0.5]
short_trip

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,day_of_week,start_id_length,end_id_length,route,ride_id_length,bad_ride_length,start_day,end_day,ride_month,ride_year
31,82B3A72973F9555D,electric_bike,2025-04-12 23:33:26.239,2025-04-12 23:33:39.559,N Paulina St & Lincoln Ave,20253.0,N Paulina St & Lincoln Ave,20253.0,41.943838,-87.671469,...,Saturday,7,7,N Paulina St & Lincoln Ave and N Paulina St & ...,16,False,2025-04-12,2025-04-12,April,2025
32,8E790254E1528CD6,electric_bike,2025-04-12 23:31:09.942,2025-04-12 23:31:29.330,N Paulina St & Lincoln Ave,20253.0,N Paulina St & Lincoln Ave,20253.0,41.943838,-87.671469,...,Saturday,7,7,N Paulina St & Lincoln Ave and N Paulina St & ...,16,False,2025-04-12,2025-04-12,April,2025
33,4617DABB59F13FF0,electric_bike,2025-04-12 23:34:20.750,2025-04-12 23:34:33.312,N Paulina St & Lincoln Ave,20253.0,N Paulina St & Lincoln Ave,20253.0,41.943838,-87.671469,...,Saturday,7,7,N Paulina St & Lincoln Ave and N Paulina St & ...,16,False,2025-04-12,2025-04-12,April,2025
34,8CCE0B14A5D7FFF4,electric_bike,2025-04-12 23:32:52.641,2025-04-12 23:33:06.954,N Paulina St & Lincoln Ave,20253.0,N Paulina St & Lincoln Ave,20253.0,41.943838,-87.671469,...,Saturday,7,7,N Paulina St & Lincoln Ave and N Paulina St & ...,16,False,2025-04-12,2025-04-12,April,2025
235,06F09B9D70D79D54,electric_bike,2025-04-23 15:32:06.472,2025-04-23 15:32:21.078,Franklin St & Jackson Blvd,TA1305000025,Franklin St & Jackson Blvd,TA1305000025,41.877708,-87.635321,...,Wednesday,12,12,Franklin St & Jackson Blvd and Franklin St & J...,16,False,2025-04-23,2025-04-23,April,2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
316353,EBC4134583451667,electric_bike,2026-03-31 17:08:31.986,2026-03-31 17:08:36.463,Sangamon St & Adams St,CHI02116,Sangamon St & Adams St,CHI02116,41.879061,-87.651325,...,Tuesday,8,8,Sangamon St & Adams St and Sangamon St & Adams St,16,False,2026-03-31,2026-03-31,March,2026
316355,B0E68A0EDDC8A9CD,electric_bike,2026-03-02 18:28:58.930,2026-03-02 18:29:25.391,University Ave & 57th St,CHI00551,University Ave & 57th St,CHI00551,41.791478,-87.599861,...,Monday,8,8,University Ave & 57th St and University Ave & ...,16,False,2026-03-02,2026-03-02,March,2026
316369,510DD9EF0C0ECDFE,electric_bike,2026-03-09 17:38:00.475,2026-03-09 17:38:26.079,University Ave & 57th St,CHI00551,University Ave & 57th St,CHI00551,41.791476,-87.600140,...,Monday,8,8,University Ave & 57th St and University Ave & ...,16,False,2026-03-09,2026-03-09,March,2026
316371,B7AE28A41C926047,electric_bike,2026-03-28 22:34:19.460,2026-03-28 22:34:33.763,University Ave & 57th St,CHI00551,University Ave & 57th St,CHI00551,41.791478,-87.599861,...,Saturday,8,8,University Ave & 57th St and University Ave & ...,16,False,2026-03-28,2026-03-28,March,2026
316372,2763A102FAC59196,electric_bike,2026-03-09 17:19:31.717,2026-03-09 17:19:34.552,Sangamon St & Washington Blvd,CHI00439,Sangamon St & Washington Blvd,CHI00439,41.883165,-87.651100,...,Monday,8,8,Sangamon St & Washington Blvd and Sangamon St ...,16,False,2026-03-09,2026-03-09,March,2026

In [93]:
year_data = year_data[(year_data.ride_length<=180) & (year_data.ride_length>=0.5)] 
#filters out rides longer than 3 hours and shorter than half a minute

In [94]:
#check ride length data type
year_data.ride_length.dtype

dtype('float64')

In [95]:
#checks ride id data type
year_data.ride_id.dtype

dtype('O')

In [96]:
#rename columns 
year_data = year_data.rename(columns={'ride_length': 'ride_length_minutes'})

In [97]:
year_data = year_data.rename(columns={'rideable_type': 'bike_type'})

In [98]:
#drop unneeded columns 
year_data=year_data.drop(columns=['start_lat', 'start_lng', 'end_lat', 'end_lng', 'bad_ride_length', 'ride_id_length', 'start_id_length', 'end_id_length'])

year_data #final cleaned and formatted table

,ride_id,bike_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,member_type,ride_length_minutes,day_of_week,route,start_day,end_day,ride_month,ride_year
0,AF3863596DF9D94B,classic_bike,2025-04-27 14:29:34.619,2025-04-27 14:36:23.584,Troy St & Elston Ave,15631,Richmond St & Diversey Ave,15645,member,6.82,Sunday,Troy St & Elston Ave and Richmond St & Diverse...,2025-04-27,2025-04-27,April,2025
1,8B38081EBE918800,electric_bike,2025-04-23 17:48:51.863,2025-04-23 17:59:06.015,Wabash Ave & Adams St,KA1503000015,Green St & Madison St,TA1307000120,member,10.24,Wednesday,Wabash Ave & Adams St and Green St & Madison St,2025-04-23,2025-04-23,April,2025
2,1C7F1DE826BBBC8D,electric_bike,2025-04-05 17:55:30.845,2025-04-05 18:05:40.032,Damen Ave & Cortland St,13133,California Ave & Fletcher St,15642,member,10.15,Saturday,Damen Ave & Cortland St and California Ave & F...,2025-04-05,2025-04-05,April,2025
3,CAD23D69A79A6C3B,classic_bike,2025-04-03 08:22:04.493,2025-04-03 08:32:06.099,Clark St & Elm St,TA1307000039,Orleans St & Merchandise Mart Plaza,TA1305000022,member,10.03,Thursday,Clark St & Elm St and Orleans St & Merchandise...,2025-04-03,2025-04-03,April,2025
4,BE241E601482E0AB,electric_bike,2025-04-15 06:09:55.293,2025-04-15 06:19:58.942,Western Ave & Walton St,KA1504000103,Damen Ave & Charleston St,13288,member,10.06,Tuesday,Western Ave & Walton St and Damen Ave & Charle...,2025-04-15,2025-04-15,April,2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
317032,1ADE06C58744ECAB,electric_bike,2026-03-02 09:11:49.421,2026-03-02 09:16:37.134,Western Ave & Lunt Ave,CHI00801,Clark St & Lunt Ave,CHI00642,member,4.80,Monday,Western Ave & Lunt Ave and Clark St & Lunt Ave,2026-03-02,2026-03-02,March,2026
317033,87819D83AF437454,classic_bike,2026-03-05 07:38:53.806,2026-03-05 07:44:13.659,Western Ave & Lunt Ave,CHI00801,Clark St & Lunt Ave,CHI00642,member,5.33,Thursday,Western Ave & Lunt Ave and Clark St & Lunt Ave,2026-03-05,2026-03-05,March,2026
317034,7E910EFCCBCF8440,electric_bike,2026-03-25 18:27:59.727,2026-03-25 18:35:06.921,DuSable Lake Shore Dr & Belmont Ave,CHI00480,Southport Ave & Waveland Ave,CHI00336,casual,7.12,Wednesday,DuSable Lake Shore Dr & Belmont Ave and Southp...,2026-03-25,2026-03-25,March,2026
317035,577CC5F21A42A372,electric_bike,2026-03-09 16:26:54.043,2026-03-09 16:29:55.413,Western Ave & Lunt Ave,CHI00801,Clark St & Lunt Ave,CHI00642,member,3.02,Monday,Western Ave & Lunt Ave and Clark St & Lunt Ave,2026-03-09,2026-03-09,March,2026
317036,EAD156B889B86C8E,electric_bike,2026-03-24 08:20:16.530,2026-03-24 08:29:20.189,Racine Ave & Webster Ave,CHI02144,Southport Ave & Waveland Ave,CHI00336,member,9.06,Tuesday,Racine Ave & Webster Ave and Southport Ave & W...,2026-03-24,2026-03-24,March,2026

In [99]:
#check final row count of table
year_data.shape

(5495030, 16)

In [100]:
year_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5495030 entries, 0 to 317036
Data columns (total 16 columns):
 #   Column               Dtype
---  ------               -----
 0   ride_id              object
 1   bike_type            object
 2   started_at           datetime64[ns]
 3   ended_at             datetime64[ns]
 4   start_station_name   object
 5   start_station_id     object
 6   end_station_name     object
 7   end_station_id       object
 8   member_type          object
 9   ride_length_minutes  float64
 10  day_of_week          object
 11  route                object
 12  start_day            object
 13  end_day              object
 14  ride_month           object
 15  ride_year            int32
dtypes: datetime64[ns](2), float64(1), int32(1), object(12)
memory usage: 691.7+ MB

In [101]:
year_data['member_type'].value_counts() #verify proportion of member type remained consistent

member_type
member    3547953
casual    1947077
Name: count, dtype: int64

In [52]:
year_data.to_csv('cyclistics_cleaned_year_data.csv', index=False) #exporting cleaned dataset for analysis