In [1]:
#This code is used to analyze the bike share data

#import numpy and pandas
import numpy as np
import pandas as pd

Import the csv and get info on it.

In [2]:
year_data=pd.read_csv(r"C:\Users\madse\OneDrive\Documents\Data Analytics Certificate\Case Study 1_ Cyclistics\cyclistics_cleaned_year_data_updated.csv")

In [3]:
year_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5495030 entries, 0 to 5495029
Data columns (total 16 columns):
 #   Column               Dtype
---  ------               -----
 0   ride_id              object
 1   bike_type            object
 2   started_at           object
 3   ended_at             object
 4   start_station_name   object
 5   start_station_id     object
 6   end_station_name     object
 7   end_station_id       object
 8   member_type          object
 9   ride_length_minutes  float64
 10  day_of_week          object
 11  route                object
 12  start_day            object
 13  end_day              object
 14  ride_month           object
 15  ride_year            int64
dtypes: float64(1), int64(1), object(14)
memory usage: 670.8+ MB

In [4]:
#begin with descriptive analysis of ride length
year_data.ride_length_minutes.describe()

count    5.495030e+06
mean     1.394342e+01
std      1.501808e+01
min      5.000000e-01
25%      5.580000e+00
50%      9.580000e+00
75%      1.669000e+01
max      1.799900e+02
Name: ride_length_minutes, dtype: float64

#### Average ride length is 13.94 minutes long.

In [5]:
#analyze ride length per member type 
year_data.groupby('member_type') ['ride_length_minutes'].agg(['mean', 'median', 'max', 'min']).round(2)

              mean  median     max  min
member_type
casual       18.07   11.66  179.99  0.5
member       11.68    8.70  179.97  0.5

In [6]:
#number of rides per member type 
year_data[['member_type']].value_counts()

member_type
member         3547953
casual         1947077
Name: count, dtype: int64

BIKE TYPE ANALYSIS

In [7]:
#analyze bike type per member type 
year_data.groupby(['member_type', 'bike_type']).size().unstack()

bike_type    classic_bike  electric_bike
member_type
casual             657599        1289478
member            1269644        2278309

In [10]:
#calculate percentage of bike type per member type 

casual_classic=round((657599/1947077)*100,2)
casual_electric=round((1289478/1947077)*100,2)
member_classic=round((1269644/3547953)*100,2)
member_electric=round((2278309/3547953)*100,2)

In [11]:
print(casual_classic)
print(casual_electric)
print(member_classic)
print(member_electric)

33.77
66.23
35.79
64.21

In [12]:
#analyze ride length average per bike type per member type 
year_data.groupby(['member_type', 'bike_type'])['ride_length_minutes'].mean().unstack().round(2)

bike_type    classic_bike  electric_bike
member_type
casual              25.02          14.53
member              12.77          11.07

DAY OF WEEK ANALYSIS

In [13]:
#Sort days of week in order 
days_order = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]
year_data['day_of_week'] = pd.Categorical(year_data['day_of_week'],
categories=days_order, ordered=True)

In [15]:
#analyze ride count per day of week per member type 
year_data.groupby(['member_type', 'day_of_week'], observed=True).size().unstack()

day_of_week  Sunday  Monday  Tuesday  Wednesday  Thursday  Friday  Saturday
member_type
casual       325875  226785   220669     217192    251501  304096    400959
member       381212  503505   572120     553981    572276  521454    443405

In [16]:
#analyze avg ride length per day of week per member type 

year_data.groupby(['member_type', 'day_of_week'],observed=True)['ride_length_minutes'].mean().unstack().round(2)

day_of_week  Sunday  Monday  Tuesday  Wednesday  Thursday  Friday  Saturday
member_type
casual        20.87   18.25    15.87      15.17     15.89   17.59     20.21
member        12.81   11.38    11.27      11.24     11.31   11.53     12.77

In [17]:
#analyze median ride length per day of week per member type 

year_data.groupby(['member_type', 'day_of_week'],observed=True)['ride_length_minutes'].median().unstack().round(2)

day_of_week  Sunday  Monday  Tuesday  Wednesday  Thursday  Friday  Saturday
member_type
casual        13.59   11.36    10.24      10.07     10.37   11.46     13.48
member         9.24    8.42     8.52       8.54      8.57    8.57      9.41

In [18]:
#create filtered data frame for only weekdays 

weekday=(year_data.day_of_week=="Monday") | (year_data.day_of_week =="Tuesday") | (year_data.day_of_week=='Wednesday') | (year_data.day_of_week=='Thursday') | (year_data.day_of_week=='Friday')

weekday = year_data[weekday]

#find ride count per member type on weekdays 
weekday[['member_type']].value_counts()

member_type
member         2723336
casual         1220243
Name: count, dtype: int64

In [19]:
#create filtered data frame for only weekends  


weekend=(year_data.day_of_week=="Saturday") | (year_data.day_of_week =="Sunday") 

weekend = year_data[weekend]

#find ride count per member type on weekends  
weekend[['member_type']].value_counts()

member_type
member         824617
casual         726834
Name: count, dtype: int64

In [20]:
#calculate proportion of rides that happened on weekdays vs weekends for each member type 
casual_weekday=round((1220243/1947077)*100,2)
member_weekday=round((2723336/3547953)*100,2)
casual_weekend=round((726834/1947077)*100,2)
member_weekend=round((824617/3547953)*100,2)

print (casual_weekday)
print (casual_weekend)
print (member_weekday) 
print (member_weekend)

62.67
37.33
76.76
23.24

In [21]:
#find average ride length for each member type on weekdays
weekday.groupby(['member_type'],observed=True)['ride_length_minutes'].mean().round(2)

member_type
casual    16.62
member    11.34
Name: ride_length_minutes, dtype: float64

In [23]:
#find average ride length for each member type on weekends 

weekend.groupby(['member_type'],observed=True)['ride_length_minutes'].mean().round(2)

member_type
casual    20.51
member    12.79
Name: ride_length_minutes, dtype: float64

MONTH OF YEAR ANALYSIS

In [24]:
#Sort months in order 

months_order = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]
year_data['ride_month'] = pd.Categorical(year_data['ride_month'],
categories=months_order, ordered=True)

In [25]:
#find ride count for each member type per month 

year_data.groupby(['member_type', 'ride_month'],observed=True)['ride_length_minutes'].size().unstack()

ride_month,January,February,March,April,May,June,July,August,September,October,November,December
member_type,,,,,,,,,,,,
casual,24026,40274,85467,105852,176802,281043,311165,326143,256816,216456,95727,27306
member,110351,157944,225144,258665,315170,380857,432766,445340,442928,415881,253129,109778

In [26]:
#find average ride length for each member type per month 

year_data.groupby(['member_type', 'ride_month'],observed=True)['ride_length_minutes'].mean().unstack().round(2)

ride_month,January,February,March,April,May,June,July,August,September,October,November,December
member_type,,,,,,,,,,,,
casual,10.37,13.15,15.50,17.03,18.89,19.75,19.47,20.02,18.09,16.39,13.57,11.26
member,9.80,10.23,10.84,10.88,11.56,12.50,12.53,12.75,12.24,11.40,10.65,10.19

In [27]:
#find average ride length per member type per year 
year_data.groupby(['member_type', 'ride_year'],observed=True)['ride_length_minutes'].mean().unstack().round(2)

ride_year     2025   2026
member_type
casual       18.41  14.05
member       11.88  10.41

In [28]:
year_data.head()

,ride_id,bike_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,member_type,ride_length_minutes,day_of_week,route,start_day,end_day,ride_month,ride_year
0,AF3863596DF9D94B,classic_bike,2025-04-27 14:29:34.619,2025-04-27 14:36:23.584,Troy St & Elston Ave,15631,Richmond St & Diversey Ave,15645,member,6.82,Sunday,Troy St & Elston Ave and Richmond St & Diverse...,2025-04-27,2025-04-27,April,2025
1,8B38081EBE918800,electric_bike,2025-04-23 17:48:51.863,2025-04-23 17:59:06.015,Wabash Ave & Adams St,KA1503000015,Green St & Madison St,TA1307000120,member,10.24,Wednesday,Wabash Ave & Adams St and Green St & Madison St,2025-04-23,2025-04-23,April,2025
2,1C7F1DE826BBBC8D,electric_bike,2025-04-05 17:55:30.845,2025-04-05 18:05:40.032,Damen Ave & Cortland St,13133,California Ave & Fletcher St,15642,member,10.15,Saturday,Damen Ave & Cortland St and California Ave & F...,2025-04-05,2025-04-05,April,2025
3,CAD23D69A79A6C3B,classic_bike,2025-04-03 08:22:04.493,2025-04-03 08:32:06.099,Clark St & Elm St,TA1307000039,Orleans St & Merchandise Mart Plaza,TA1305000022,member,10.03,Thursday,Clark St & Elm St and Orleans St & Merchandise...,2025-04-03,2025-04-03,April,2025
4,BE241E601482E0AB,electric_bike,2025-04-15 06:09:55.293,2025-04-15 06:19:58.942,Western Ave & Walton St,KA1504000103,Damen Ave & Charleston St,13288,member,10.06,Tuesday,Western Ave & Walton St and Damen Ave & Charle...,2025-04-15,2025-04-15,April,2025

TIME OF DAY ANALYSIS

In [29]:
#create a filter for morning between 5AM-11AM and get ride count per user type at this time 
year_data['started_at'] = pd.to_datetime(year_data['started_at'])

morning=(year_data.started_at.dt.hour>=5) & (year_data.started_at.dt.hour<=11)
morning=year_data[morning]
morning['member_type'].value_counts()

member_type
member    1069353
casual     413135
Name: count, dtype: int64

In [30]:
#create a filter for afternoon between 11AM-5PM and get ride count per user type at this time 

year_data['started_at'] = pd.to_datetime(year_data['started_at'])

afternoon=(year_data.started_at.dt.hour>11) & (year_data.started_at.dt.hour<=16)
afternoon=year_data[afternoon]
afternoon['member_type'].value_counts()

member_type
member    1135739
casual     711724
Name: count, dtype: int64

In [31]:
#create a filter for evening between 5pm-9pm and get ride count per user type at this time 

evening=(year_data.started_at.dt.hour>16) & (year_data.started_at.dt.hour<=21)
evening=year_data[evening]
evening['member_type'].value_counts()

member_type
member    1133092
casual     622586
Name: count, dtype: int64

In [39]:
#create a filter for night between 9PM and 5AM and get ride count per user type at this time 

night=(year_data.started_at.dt.hour>21) & (year_data.started_at.dt.hour<24) | (year_data.started_at.dt.hour<5)
night=year_data[night]
night['member_type'].value_counts()

member_type
member    209769
casual    199632
Name: count, dtype: int64

In [40]:
#for morning, group by day of week
morning.groupby(['member_type', 'day_of_week'], observed=True).size().unstack()

day_of_week  Sunday  Monday  Tuesday  Wednesday  Thursday  Friday  Saturday
member_type
casual        72233   48164    50169      48057     54583   57487     82442
member        97084  154036   187862     178878    183906  149392    118195

In [41]:
#for afternoon, group by day of week

afternoon.groupby(['member_type', 'day_of_week'], observed=True).size().unstack()

day_of_week  Sunday  Monday  Tuesday  Wednesday  Thursday  Friday  Saturday
member_type
casual       140160   81263    68968      64487     81030  109880    165936
member       152913  152422   162957     157546    167224  174395    168282

In [42]:
#for evening, group by day of week

evening.groupby(['member_type', 'day_of_week'], observed=True).size().unstack()

day_of_week  Sunday  Monday  Tuesday  Wednesday  Thursday  Friday  Saturday
member_type
casual        75630   78896    84885      86225     92769  102676    101505
member        97951  176661   198882     193214    192028  162193    112163

In [43]:
#for night, group by day of week

night.groupby(['member_type', 'day_of_week'], observed=True).size().unstack()

day_of_week  Sunday  Monday  Tuesday  Wednesday  Thursday  Friday  Saturday
member_type
casual        37852   18462    16647      18423     23119   34053     51076
member        33264   20386    22419      24343     29118   35474     44765